- name: Deploy InTheOfficeBot
  hosts: all
  become: true
  remote_user: "{{ HETZNER_USER }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3.12 
    dir: "{{ APP_PATH }}"
    app_name: "InTheOfficeBot"
    git_repo: "https://github.com/golovko/InTheOffice.git"
    git_branch: "main"
    dotnet_sdk_version: "9.0"
    app_path: "{{ dir }}/InTheOffice"
    publish_folder: "{{ app_path }}/publish"
    service_name: "{{ app_name }}.service"
    service_port: 5000
    environment_vars:
      - key: "BOT_TOKEN"
        value: "{{ lookup('env', 'BOT_TOKEN') }}"
      - key: "CONNECTION_STRING"
        value: "{{ lookup('env', 'CONNECTION_STRING') }}"
  roles:
     - role: deploy_service  