- name: Stop and remove old container if it exists
  docker_container:
    name: intheofficebot_container
    state: absent

- name: Remove old Docker image
  docker_image:
    name: intheofficebot
    state: absent 

- name: Build docker image
  docker_image:
    name: intheofficebot
    force_source: true
    source: build
    build:
      path: "{{ APP_PATH }}"
      dockerfile: .docker/Dockerfile

- name: Run docker container
  docker_container:
    user: root
    name: intheofficebot_container
    image: intheofficebot
    recreate: true
    restart: true
    ports: 
      - "{{ PORT }}:{{ PORT }}"
    env:
      BotToken: "{{ BOT_TOKEN }}"
    volumes:
      - /home/ubuntu/data:/app/data 

